from pathlib import Path
import pandas as pd

pp = Path(r'F:\Max\U920')
path_res = Path(r'F:\Max\U920')

A = pd.read_csv(pp / 'U920_A.csv')
B = pd.read_csv(pp / 'U920_B.csv')
C = pd.read_csv(pp / 'U920_C.csv')
D = pd.read_csv(pp / 'U920_D.csv')
E = pd.read_csv(pp / 'U920_E.csv')
F = pd.read_csv(pp / 'U920_F.csv')
G = pd.read_csv(pp / 'U920_G.csv')
H = pd.read_csv(pp / 'U920_H.csv')
I = pd.read_csv(pp / 'U920_I.csv')
J = pd.read_csv(pp / 'U920_J.csv')
K = pd.read_csv(pp / 'U920_K.csv')
L = pd.read_csv(pp / 'U920_L.csv')
M = pd.read_csv(pp / 'U920_M.csv')
N = pd.read_csv(pp / 'U920_N.csv')
O = pd.read_csv(pp / 'U920_O.csv')
P = pd.read_csv(pp / 'U920_P.csv')
Q = pd.read_csv(pp / 'U920_Q.csv')
R = pd.read_csv(pp / 'U920_R.csv')
S = pd.read_csv(pp / 'U920_S.csv')
T = pd.read_csv(pp / 'U920_T.csv')
U = pd.read_csv(pp / 'U920_U.csv')
V = pd.read_csv(pp / 'U920_V.csv')
W = pd.read_csv(pp / 'U920_W.csv')
YZ = pd.read_csv(pp/ 'U920_YZ.csv')
se = pd.read_csv(pp/ 'U920_ÅÄÖ.csv')


A = A.drop(columns='Unnamed: 0')
B = B.drop(columns='Unnamed: 0')
C = C.drop(columns='Unnamed: 0')
D = D.drop(columns='Unnamed: 0')
E = E.drop(columns='Unnamed: 0')
F = F.drop(columns='Unnamed: 0')
G = G.drop(columns='Unnamed: 0')
H = H.drop(columns='Unnamed: 0')
I = I.drop(columns='Unnamed: 0')
J = J.drop(columns='Unnamed: 0')
K = K.drop(columns='Unnamed: 0')
L = L.drop(columns='Unnamed: 0')
M = M.drop(columns='Unnamed: 0')
N = N.drop(columns='Unnamed: 0')
O = O.drop(columns='Unnamed: 0')
P = P.drop(columns='Unnamed: 0')
Q = Q.drop(columns='Unnamed: 0')
R = R.drop(columns='Unnamed: 0')
S = S.drop(columns='Unnamed: 0')
T = T.drop(columns='Unnamed: 0')
U = U.drop(columns='Unnamed: 0')
V = V.drop(columns='Unnamed: 0')
W = W.drop(columns='Unnamed: 0')
YZ = YZ.drop(columns='Unnamed: 0')
se = se.drop(columns='Unnamed: 0')

tot = pd.concat([A,B,C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, YZ, se], ignore_index=True)
tot.to_csv(path_res / 'U920_complete.csv')